# APS Failure UCI

https://archive.ics.uci.edu/ml/datasets/APS+Failure+at+Scania+Trucks

In [1]:
import pandas as pd
import numpy as np

from sklearn import tree
import matplotlib.pyplot as plt

In [2]:
dirpath = r'C:\Users\joeba\OneDrive\Documents\ML\Data\aps failure uci'

df = pd.read_csv(dirpath+'/aps_failure_training_set.csv', skiprows=20)

df.head(10)

,class,aa_000,ab_000,ac_000,ad_000,ae_000,af_000,ag_000,ag_001,ag_002,...,ee_002,ee_003,ee_004,ee_005,ee_006,ee_007,ee_008,ee_009,ef_000,eg_000
0,neg,76698,na,2130706438,280,0,0,0,0,0,...,1240520,493384,721044,469792,339156,157956,73224,0,0,0
1,neg,33058,na,0,na,0,0,0,0,0,...,421400,178064,293306,245416,133654,81140,97576,1500,0,0
2,neg,41040,na,228,100,0,0,0,0,0,...,277378,159812,423992,409564,320746,158022,95128,514,0,0
3,neg,12,0,70,66,0,10,0,0,0,...,240,46,58,44,10,0,0,0,4,32
4,neg,60874,na,1368,458,0,0,0,0,0,...,622012,229790,405298,347188,286954,311560,433954,1218,0,0
5,neg,38312,na,2130706432,218,0,0,0,0,0,...,388574,288278,900430,300412,1534,338,856,0,0,0
6,neg,14,0,6,na,0,0,0,0,0,...,168,48,60,28,0,0,0,0,0,0
7,neg,102960,na,2130706432,116,0,0,0,0,0,...,715518,384948,915978,1052166,1108672,341532,129504,7832,0,0
8,neg,78696,na,0,na,0,0,0,0,0,...,699290,362510,1190028,1012704,160090,63216,41202,4,0,0
9,pos,153204,0,182,na,0,0,0,0,0,...,129862,26872,34044,22472,34362,0,0,0,0,0

In [3]:
df['class'].value_counts()

neg    59000
pos     1000
Name: class, dtype: int64

In [4]:
df = df.replace('na', np.NaN)
df = df.fillna(0)

df.isna().sum()

class     0
aa_000    0
ab_000    0
ac_000    0
ad_000    0
         ..
ee_007    0
ee_008    0
ee_009    0
ef_000    0
eg_000    0
Length: 171, dtype: int64

In [5]:
d = {'pos': 1, 'neg': 0}
df['class'] = df['class'].map(d)

df = df.astype(float)

In [6]:
features = list(df.columns)[1:]

In [39]:

X = df[features]
y = df['class']

#dt = tree.DecisionTreeClassifier(min_weight_fraction_leaf=0.01)
#dt = tree.DecisionTreeClassifier(class_weight='balanced')
dt = tree.DecisionTreeClassifier(class_weight={1:2})
dt = dt.fit(X,y)

In [17]:
"""from dtreeviz.trees import *

viz = dtreeviz(dt, 
               x_data=X,
               y_data=y,
               target_name='class',
               feature_names=features, 
               class_names=list(['neg', 'pos']), 
               title="Decision Tree - APS failure data set"
              )
viz
"""

'from dtreeviz.trees import *\n\nviz = dtreeviz(dt, \n               x_data=X,\n               y_data=y,\n               target_name=\'class\',\n               feature_names=features, \n               class_names=list([\'neg\', \'pos\']), \n               title="Decision Tree - APS failure data set"\n              )\nviz\n'

In [18]:
text_representation = tree.export_text(dt)
print(text_representation)

|--- feature_8 <= 469226.00
|   |--- feature_103 <= 36182078.00
|   |   |--- feature_25 <= 4557878.00
|   |   |   |--- feature_8 <= 139996.00
|   |   |   |   |--- feature_147 <= 2969951.00
|   |   |   |   |   |--- feature_66 <= 13825.00
|   |   |   |   |   |   |--- feature_12 <= 20219913.00
|   |   |   |   |   |   |   |--- feature_117 <= 25907116.00
|   |   |   |   |   |   |   |   |--- feature_133 <= 41235.00
|   |   |   |   |   |   |   |   |   |--- feature_28 <= 2861227.00
|   |   |   |   |   |   |   |   |   |   |--- feature_41 <= 121331.00
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 42
|   |   |   |   |   |   |   |   |   |   |--- feature_41 >  121331.00
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |   |   |--- feature_28 >  2861227.00
|   |   |   |   |   |   |   |   |   |   |--- class: 1.0
|   |   |   |   |   |   |   |   |--- feature_133 >  41235.00
|   |   |   |   |   |   |   |   |   |--- class: 1.0
|   |   |   |   |   |   |   |--- feature_117 >  25907116.00
|   |   |   |   |   |   |   |   |--- class: 1.0
|   |   |   |   |   |   |--- feature_12 >  20219913.00
|   |   |   |   |   |   |   |--- feature_52 <= 12056929.00
|   |   |   |   |   |   |   |   |--- class: 1.0
|   |   |   |   |   |   |   |--- feature_52 >  12056929.00
|   |   |   |   |   |   |   |   |--- feature_23 <= 46154826.00
|   |   |   |   |   |   |   |   |   |--- feature_33 <= 535.00
|   |   |   |   |   |   |   |   |   |   |--- feature_125 <= 28706643.00
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 18
|   |   |   |   |   |   |   |   |   |   |--- feature_125 >  28706643.00
|   |   |   |   |   |   |   |   |   |   |   |--- class: 1.0
|   |   |   |   |   |   |   |   |   |--- feature_33 >  535.00
|   |   |   |   |   |   |   |   |   |   |--- class: 1.0
|   |   |   |   |   |   |   |   |--- feature_23 >  46154826.00
|   |   |   |   |   |   |   |   |   |--- class: 1.0
|   |   |   |   |   |--- feature_66 >  13825.00
|   |   |   |   |   |   |--- class: 1.0
|   |   |   |   |--- feature_147 >  2969951.00
|   |   |   |   |   |--- class: 1.0
|   |   |   |--- feature_8 >  139996.00
|   |   |   |   |--- feature_163 <= 4188971.00
|   |   |   |   |   |--- feature_38 <= 46757.00
|   |   |   |   |   |   |--- feature_83 <= 14314568.00
|   |   |   |   |   |   |   |--- feature_84 <= 69688.00
|   |   |   |   |   |   |   |   |--- feature_42 <= 37647.00
|   |   |   |   |   |   |   |   |   |--- feature_79 <= 322620.00
|   |   |   |   |   |   |   |   |   |   |--- feature_149 <= 10775780.00
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 3
|   |   |   |   |   |   |   |   |   |   |--- feature_149 >  10775780.00
|   |   |   |   |   |   |   |   |   |   |   |--- class: 1.0
|   |   |   |   |   |   |   |   |   |--- feature_79 >  322620.00
|   |   |   |   |   |   |   |   |   |   |--- feature_152 <= 4993.00
|   |   |   |   |   |   |   |   |   |   |   |--- class: 1.0
|   |   |   |   |   |   |   |   |   |   |--- feature_152 >  4993.00
|   |   |   |   |   |   |   |   |   |   |   |--- class: 1.0
|   |   |   |   |   |   |   |   |--- feature_42 >  37647.00
|   |   |   |   |   |   |   |   |   |--- feature_25 <= 562497.00
|   |   |   |   |   |   |   |   |   |   |--- class: 1.0
|   |   |   |   |   |   |   |   |   |--- feature_25 >  562497.00
|   |   |   |   |   |   |   |   |   |   |--- class: 1.0
|   |   |   |   |   |   |   |--- feature_84 >  69688.00
|   |   |   |   |   |   |   |   |--- feature_79 <= 14850.00
|   |   |   |   |   |   |   |   |   |--- class: 1.0
|   |   |   |   |   |   |   |   |--- feature_79 >  14850.00
|   |   |   |   |   |   |   |   |   |--- class: 1.0
|   |   |   |   |   |   |--- feature_83 >  14314568.00
|   |   |   |   |   |   |   |--- feature_162 <= 5523629.00
|   |   |   |   |   |   |   |   |--- class: 1.0
|   |   |   |   |   |   |   |--- feature_162 >  5523629.00
|   |   |   |   |   |   |   |   |--- class: 0.0
|   |   |   |   |   |--- feature_38 >  46757.00
|   |   |   |   |   |   |--- feature_152 <= 759643.00
|   |   |   |   |   |   |   |--- feature_78 <= 621260.00
|   |   |   |   |   |   |   |   |--- feature_17 <= 123229.00
|   |   |   |   |   |   |   |   |   |--- feature_71 <= 615010.00
|   |   |   |   |   |   |   |   |   |   |--- feature_168 <= 2.00
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 6
|   |   |   |   |   |   |   |   |   |   |--- feature_168 >  2.00
|   |   |   |   |   |   |   |   |   |   |   |--- class: 1.0
|   |   |   |   |   |   |   |   |   |--- feature_71 >  615010.00
|   |   |   |   |   |   |   |   |   |   |--- class: 1.0
|   |   |   |   |   |   |   |   |--- feature_17 >  123229.00
|   |   |   |   |   |   |   |   |   |--- class: 1.0
|   |   |   |   |   |   |   |--- feature_78 >  621260.00
|   |   |   |   |   |   |   |   |--- class: 1.0
|   |   |   |   |   |   |--- feature_152 >  759643.00
|   |   |   |   |   |   |   |--- class: 1.0
|   |   |   |   |--- feature_163 >  4188971.00
|   |   |   |   |   |--- class: 1.0
|   |   |--- feature_25 >  4557878.00
|   |   |   |--- feature_32 <= 3165220.00
|   |   |   |   |--- feature_21 <= 4951811.00
|   |   |   |   |   |--- feature_37 <= 917691.00
|   |   |   |   |   |   |--- feature_134 <= 13755.00
|   |   |   |   |   |   |   |--- feature_28 <= 3208589.00
|   |   |   |   |   |   |   |   |--- feature_72 <= 841870.00
|   |   |   |   |   |   |   |   |   |--- feature_121 <= 13289.00
|   |   |   |   |   |   |   |   |   |   |--- feature_143 <= 1135456.00
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 35
|   |   |   |   |   |   |   |   |   |   |--- feature_143 >  1135456.00
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |   |   |--- feature_121 >  13289.00
|   |   |   |   |   |   |   |   |   |   |--- feature_165 <= 878619.00
|   |   |   |   |   |   |   |   |   |   |   |--- class: 1.0
|   |   |   |   |   |   |   |   |   |   |--- feature_165 >  878619.00
|   |   |   |   |   |   |   |   |   |   |   |--- class: 1.0
|   |   |   |   |   |   |   |   |--- feature_72 >  841870.00
|   |   |   |   |   |   |   |   |   |--- feature_124 <= 680.00
|   |   |   |   |   |   |   |   |   |   |--- class: 1.0
|   |   |   |   |   |   |   |   |   |--- feature_124 >  680.00
|   |   |   |   |   |   |   |   |   |   |--- class: 1.0
|   |   |   |   |   |   |   |--- feature_28 >  3208589.00
|   |   |   |   |   |   |   |   |--- feature_50 <= 1.00
|   |   |   |   |   |   |   |   |   |--- class: 1.0
|   |   |   |   |   |   |   |   |--- feature_50 >  1.00
|   |   |   |   |   |   |   |   |   |--- class: 1.0
|   |   |   |   |   |   |--- feature_134 >  13755.00
|   |   |   |   |   |   |   |--- feature_161 <= 2451581.00
|   |   |   |   |   |   |   |   |--- class: 1.0
|   |   |   |   |   |   |   |--- feature_161 >  2451581.00
|   |   |   |   |   |   |   |   |--- class: 0.0
|   |   |   |   |   |--- feature_37 >  917691.00
|   |   |   |   |   |   |--- feature_143 <= 440801.00
|   |   |   |   |   |   |   |--- feature_36 <= 7533162.00
|   |   |   |   |   |   |   |   |--- feature_11 <= 2458336.00
|   |   |   |   |   |   |   |   |   |--- class: 1.0
|   |   |   |   |   |   |   |   |--- feature_11 >  2458336.00
|   |   |   |   |   |   |   |   |   |--- feature_57 <= 7294657.00
|   |   |   |   |   |   |   |   |   |   |--- feature_71 <= 776880.00
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 14
|   |   |   |   |   |   |   |   |   |   |--- feature_71 >  776880.00
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |   |   |--- feature_57 >  7294657.00
|   |   |   |   |   |   |   |   |   |   |--- feature_58 <= 3477583.00
|   |   |   |   |   |   |   |   |   |   |   |--- class: 1.0
|   |   |   |   |   |   |   |   |   |   |--- feature_58 >  3477583.00
|   |   |   |   |   |   |   |   |   |   |   |--- class: 1.0
|   |   |   |   |   |   |   |--- feature_36 >  7533162.00
|   |   |   |   |   |   |   |   |--- feature_62 <= 50709188.00
|   |   |   |   |   |   |   |   |   |--- class: 1.0
|   |   |   |   |   |   |   |   |--- feature_62 >  50709188.00
|   |   |   |   |   |   |   |   |   |--- class: 1.0
|   |   |   |   |   |   |--- feature_143 >  440801.00
|   |   |   |   |   |   |   |--- feature_39 <= 12009435.00
|   |   |   |   |   |   |   |   |--- feature_113 <= 46174.00
|   |   |   |   |   |   |   |   |   |--- class: 1.0
|   |   |   |   |   |   |   |   |--- feature_113 >  46174.00
|   |   |   |   |   |   |   |   |   |--- class: 0.0
|   |   |   |   |   |   |   |--- feature_39 >  12009435.00
|   |   |   |   |   |   |   |   |--- class: 1.0
|   |   |   |   |--- feature_21 >  4951811.00
|   |   |   |   |   |--- feature_165 <= 1279486.00
|   |   |   |   |   |   |--- feature_152 <= 65534.00
|   |   |   |   |   |   |   |--- class: 1.0
|   |   |   |   |   |   |--- feature_152 >  65534.00
|   |   |   |   |   |   |   |--- feature_111 <= 98273708.00
|   |   |   |   |   |   |   |   |--- class: 1.0
|   |   |   |   |   |   |   |--- feature_111 >  98273708.00
|   |   |   |   |   |   |   |   |--- class: 0.0
|   |   |   |   |   |--- feature_165 >  1279486.00
|   |   |   |   |   |   |--- feature_149 <= 259990.00
|   |   |   |   |   |   |   |--- feature_107 <= 4355.00
|   |   |   |   |   |   |   |   |--- class: 1.0
|   |   |   |   |   |   |   |--- feature_107 >  4355.00
|   |   |   |   |   |   |   |   |--- class: 0.0
|   |   |   |   |   |   |--- feature_149 >  259990.00
|   |   |   |   |   |   |   |--- class: 1.0
|   |   |   |--- feature_32 >  3165220.00
|   |   |   |   |--- feature_115 <= 15242104.00
|   |   |   |   |   |--- feature_51 <= 2.00
|   |   |   |   |   |   |--- class: 1.0
|   |   |   |   |   |--- feature_51 >  2.00
|   |   |   |   |   |   |--- class: 1.0
|   |   |   |   |--- feature_115 >  15242104.00
|   |   |   |   |   |--- class: 0.0
|   |--- feature_103 >  36182078.00
|   |   |--- feature_120 <= 13155.00
|   |   |   |--- feature_45 <= 355289.00
|   |   |   |   |--- class: 0.0
|   |   |   |--- feature_45 >  355289.00
|   |   |   |   |--- class: 1.0
|   |   |--- feature_120 >  13155.00
|   |   |   |--- feature_69 <= 14865300.00
|   |   |   |   |--- class: 1.0
|   |   |   |--- feature_69 >  14865300.00
|   |   |   |   |--- feature_161 <= 6609746.00
|   |   |   |   |   |--- class: 0.0
|   |   |   |   |--- feature_161 >  6609746.00
|   |   |   |   |   |--- feature_94 <= 99157964.00
|   |   |   |   |   |   |--- class: 1.0
|   |   |   |   |   |--- feature_94 >  99157964.00
|   |   |   |   |   |   |--- class: 1.0
|--- feature_8 >  469226.00
|   |--- feature_38 <= 389508.00
|   |   |--- feature_94 <= 5638356.50
|   |   |   |--- class: 0.0
|   |   |--- feature_94 >  5638356.50
|   |   |   |--- feature_103 <= 647388.00
|   |   |   |   |--- class: 1.0
|   |   |   |--- feature_103 >  647388.00
|   |   |   |   |--- class: 1.0
|   |--- feature_38 >  389508.00
|   |   |--- feature_18 <= 292.00
|   |   |   |--- feature_79 <= 345010.00
|   |   |   |   |--- feature_97 <= 9435.00
|   |   |   |   |   |--- feature_107 <= 1559.00
|   |   |   |   |   |   |--- class: 1.0
|   |   |   |   |   |--- feature_107 >  1559.00
|   |   |   |   |   |   |--- feature_73 <= 784790.00
|   |   |   |   |   |   |   |--- feature_41 <= 39893.00
|   |   |   |   |   |   |   |   |--- feature_86 <= 106897.00
|   |   |   |   |   |   |   |   |   |--- feature_29 <= 237975.00
|   |   |   |   |   |   |   |   |   |   |--- class: 0.0
|   |   |   |   |   |   |   |   |   |--- feature_29 >  237975.00
|   |   |   |   |   |   |   |   |   |   |--- class: 1.0
|   |   |   |   |   |   |   |   |--- feature_86 >  106897.00
|   |   |   |   |   |   |   |   |   |--- class: 1.0
|   |   |   |   |   |   |   |--- feature_41 >  39893.00
|   |   |   |   |   |   |   |   |--- feature_116 <= 3194269.00
|   |   |   |   |   |   |   |   |   |--- class: 1.0
|   |   |   |   |   |   |   |   |--- feature_116 >  3194269.00
|   |   |   |   |   |   |   |   |   |--- class: 1.0
|   |   |   |   |   |   |--- feature_73 >  784790.00
|   |   |   |   |   |   |   |--- feature_13 <= 299936.00
|   |   |   |   |   |   |   |   |--- class: 1.0
|   |   |   |   |   |   |   |--- feature_13 >  299936.00
|   |   |   |   |   |   |   |   |--- class: 1.0
|   |   |   |   |--- feature_97 >  9435.00
|   |   |   |   |   |--- feature_26 <= 5.00
|   |   |   |   |   |   |--- class: 1.0
|   |   |   |   |   |--- feature_26 >  5.00
|   |   |   |   |   |   |--- class: 1.0
|   |   |   |--- feature_79 >  345010.00
|   |   |   |   |--- feature_54 <= 3766779.00
|   |   |   |   |   |--- class: 1.0
|   |   |   |   |--- feature_54 >  3766779.00
|   |   |   |   |   |--- class: 1.0
|   |   |--- feature_18 >  292.00
|   |   |   |--- feature_64 <= 410.00
|   |   |   |   |--- class: 1.0
|   |   |   |--- feature_64 >  410.00
|   |   |   |   |--- class: 1.0

In [19]:
dt.tree_

In [20]:
tst = pd.read_csv(dirpath+'/aps_failure_test_set.csv', skiprows=20)

tst = tst.replace('na', np.NaN)
tst = tst.fillna(0)

tst['class'] = tst['class'].map(d)
tst = tst.astype(float)

tst

,class,aa_000,ab_000,ac_000,ad_000,ae_000,af_000,ag_000,ag_001,ag_002,...,ee_002,ee_003,ee_004,ee_005,ee_006,ee_007,ee_008,ee_009,ef_000,eg_000
0,0.0,60.0,0.0,2.000000e+01,12.0,0.0,0.0,0.0,0.0,0.0,...,1098.0,138.0,412.0,654.0,78.0,88.0,0.0,0.0,0.0,0.0
1,0.0,82.0,0.0,6.800000e+01,40.0,0.0,0.0,0.0,0.0,0.0,...,1068.0,276.0,1620.0,116.0,86.0,462.0,0.0,0.0,0.0,0.0
2,0.0,66002.0,2.0,2.120000e+02,112.0,0.0,0.0,0.0,0.0,0.0,...,495076.0,380368.0,440134.0,269556.0,1315022.0,153680.0,516.0,0.0,0.0,0.0
3,0.0,59816.0,0.0,1.010000e+03,936.0,0.0,0.0,0.0,0.0,0.0,...,540820.0,243270.0,483302.0,485332.0,431376.0,210074.0,281662.0,3232.0,0.0,0.0
4,0.0,1814.0,0.0,1.560000e+02,140.0,0.0,0.0,0.0,0.0,0.0,...,7646.0,4144.0,18466.0,49782.0,3176.0,482.0,76.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15995,0.0,81852.0,0.0,2.130706e+09,892.0,0.0,0.0,0.0,0.0,0.0,...,632658.0,273242.0,510354.0,373918.0,349840.0,317840.0,960024.0,25566.0,0.0,0.0
15996,0.0,18.0,0.0,5.200000e+01,46.0,8.0,26.0,0.0,0.0,0.0,...,266.0,44.0,46.0,14.0,2.0,0.0,0.0,0.0,0.0,0.0
15997,0.0,79636.0,0.0,1.670000e+03,1518.0,0.0,0.0,0.0,0.0,0.0,...,806832.0,449962.0,778826.0,581558.0,375498.0,222866.0,358934.0,19548.0,0.0,0.0
15998,0.0,110.0,0.0,3.600000e+01,32.0,0.0,0.0,0.0,0.0,0.0,...,588.0,210.0,180.0,544.0,1004.0,1338.0,74.0,0.0,0.0,0.0
15999,0.0,8.0,0.0,6.000000e+00,4.0,2.0,2.0,0.0,0.0,0.0,...,46.0,10.0,48.0,14.0,42.0,46.0,0.0,0.0,0.0,0.0

In [21]:
tX = tst[features]
ty = tst['class']

In [40]:
pred = dt.predict(tX)

In [41]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(ty, pred)
cm

array([[15552,    73],
       [  124,   251]], dtype=int64)

In [42]:
from sklearn.metrics import classification_report

target_names = ['neg', 'pos']
print(classification_report(ty, pred, target_names=target_names))

              precision    recall  f1-score   support

         neg       0.99      1.00      0.99     15625
         pos       0.77      0.67      0.72       375

    accuracy                           0.99     16000
   macro avg       0.88      0.83      0.86     16000
weighted avg       0.99      0.99      0.99     16000

In [38]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(n_estimators=250, random_state=1223, class_weight={1:0.49})
rf = rf.fit(X,y)

rf_pred = rf.predict(tX)

rf_cm = confusion_matrix(ty, rf_pred)
print(rf_cm)
print()
print(classification_report(ty, rf_pred, target_names=target_names))

[[15606    19]
 [  100   275]]

              precision    recall  f1-score   support

         neg       0.99      1.00      1.00     15625
         pos       0.94      0.73      0.82       375

    accuracy                           0.99     16000
   macro avg       0.96      0.87      0.91     16000
weighted avg       0.99      0.99      0.99     16000